version: '3.8'
name: codeigniter

services:

  codeigniter:
    build: .
    container_name: codeigniter
    working_dir: /var/www/html/app
    ports:
      - "8080:8080"
    volumes:
      - ../src:/var/www/html/app
    depends_on:
      - mysql


  mysql:
    container_name: mysql
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=tutorial
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=tutorial
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysqldata: 